[build]
target = "wasm32-wasi"
rustflags = [
    "--cfg",
    "wasmedge",
    "--cfg",
    "tokio_unstable",
    "-C",
    "target-feature=+bulk-memory",
]

[target.wasm32-wasi]
runner = "wasmedge --dir=.:. "
